### ISSUE TITLE
SimpleMapJodaTimeMarshaller is not initialized in unit tests

### ISSUE THREAD

**Issue by tcrossland** [gpc/joda-time#14]
Restoring `_Events.groovy` script (removed by https://github.com/gpc/joda-time/commit/f259c33e06e65e97cdb05345ba0d4f56b7cebf5b) fixes the issue (PR #13).

**Comment by tcrossland** [comment]
Resolved by #13

**Comment by gregopet** [comment]
Hi, as far as I can tell this change is not included in the currently published SNAPSHOT jar, any chance of updating the snapshot?

**Comment by gregopet** [comment]
Working solution for unit tests:

```
def setupSpec() {
	SimpleMapJodaTimeMarshaller.initialize();
}
```
